import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class ContentService {

  isEnglish:boolean = true;
  now = {
    'products': 'Products',
    'about': 'About us',
    'contact': 'Contact',
    'liv_innovation': 'LIV Innovation',
    'title_sub_1': 'Your partner for innovative automation solutions',
    'title_sub_2': 'Discover how our software can revolutionize your can revolutionize your business.',
    'learn_more': 'Learn More',
    'product_1': 'Innovation',
    'product_1_desc': 'Ready to optimize your business process and increase your productivity? Immerse yourself in the world of automation with LIV Innovation, your expert for tailor-made, innovative software solutions.',
    'product_2': 'Efficiency',
    'product_2_desc': 'In an ever-changing business world, efficiency is the key to success. We offer tailor-made automation solutions to optimize your operational business processes and take your company to the next level.',
    'product_3': 'Integration',
    'product_3_desc': 'Do you want to automate manual processes and integrate them into your existing workflow? At LIV Innovation, we offer automation solutions tailored to your specific needs.',
    'about_us': 'LIV Innovation aims to help companies work smarter and more efficiently. We believe in the power of automation to take over repetitive tasks and free up human resources for creative and strategic challenges.',
    'vision': 'Our Vision & Mission',
    'vision_mission': 'Our vision is to create a world where technology enhances human performance and helps companies achieve their goals.',
    'hello': 'Hello!',
    'love_to_hear': 'We’d love to hear from you.Here’s how you can reach us...',
    'imprint': 'Imprint',
    'data_protection': 'Data protection',
    'address': 'Bornheimer Landwehr 33, 60385 Frankfurt',
    'mobile': 'Phone +49 179 221 1285',
    'mail': 'E-mail: info@liv-innovation.com',
    'imprint_content_1': 'Sales tax identification number according to § 27a UStG: follows...........',
    'liability': 'Limitation of liability:',
    'liability_1': 'Contents of the LIV Innovation website',
    'liability_2': "The content of the LIV Innovation website has been compiled with the greatest possible care. However, LIV Innovation assumes no liability for the accuracy, completeness and timeliness of the content provided. The use of the retrievable content is at the user's own risk.",
    'external': 'External links:',
    'external_1': 'The LIV Innovation website contains links to third-party websites ("external links"). These websites are subject to the liability of the respective operators. When the external links were first created, LIV Innovation checked the third-party content for any legal violations. No legal violations were apparent at that time.',
    'external_2': 'LIV Innovation has no influence whatsoever on the current and future design and content of the linked pages. LIV Innovation therefore expressly distances itself from any illegal or immoral content on the linked pages.',
    'external_3': 'For illegal, incorrect or incomplete contents and in particular for damages resulting from the use or non-use of the information offered via the link, the provider of the page to which reference is made is solely liable, but not LIV Innovation, which merely refers to the publication by setting the link.',
    'external_4': 'The inclusion of external links does not mean that LIV Innovation adopts the content behind the reference or link as its own. LIV Innovation cannot reasonably be expected to constantly monitor these external links without concrete evidence of legal violations. However, such external links will be deleted immediately if we become aware of any legal violations.',
    'privacy': 'Privacy policy',
    'privacy_1': '1. Data protection at a glance',
    'privacy_1_1': 'General information',
    'privacy_1_2': 'The following information provides a simple overview of what happens to your personal data when you visit this website. Personal data is any data that can be used to identify you personally. Detailed information on the subject of data protection can be found in our data protection declaration listed below this text.',
    'privacy_1_3': 'Data collection on this website',
    'privacy_1_4': 'Who is responsible for data collection on this website?',
    'privacy_1_5': 'Data processing on this website is carried out by the website operator. You can find their contact details in the "Information on the controller" section of this privacy policy.',
    'privacy_1_6': 'How do we collect your data?',
    'privacy_1_7': 'On the one hand, your data is collected when you provide it to us. This may, for example, be data that you enter in a contact form.',
    'privacy_1_8': 'Other data is collected automatically or with your consent by our IT systems when you visit the website. This is primarily technical data (e.g. internet browser, operating system or time of page view). This data is collected automatically as soon as you enter this website.',
    'privacy_1_9': 'What do we use your data for?',
    'privacy_1_10': 'Some of the data is collected to ensure that the website is provided without errors. Other data may be used to analyze your user behavior.',
    'privacy_1_11': 'What rights do you have regarding your data?',
    'privacy_1_12': 'You have the right to receive information about the origin, recipient and purpose of your stored personal data free of charge at any time. You also have the right to request the correction or deletion of this data. If you have given your consent to data processing, you can revoke this consent at any time for the future. You also have the right to request the restriction of the processing of your personal data under certain circumstances. You also have the right to lodge a complaint with the competent supervisory authority.',
    'privacy_1_13': 'You can contact us at any time if you have further questions on the subject of data protection.',
    'privacy_1_14': 'Analysis tools and tools from third-party providers',
    'privacy_1_15': 'When you visit this website, your surfing behavior may be statistically evaluated. This is mainly done with so-called analysis programs.',
    'privacy_1_16': 'Detailed information on these analysis programs can be found in the following privacy policy.',
    'hosting': '2. Hosting',
    'hosting_1': 'We host the content of our website with the following provider:',
    'hosting_2': 'IONOS',
    'hosting_3': "The provider is IONOS SE, Elgendorfer Str. 57, 56410 Montabaur (hereinafter referred to as IONOS). When you visit our website, IONOS collects various log files including your IP addresses. Details can be found in the IONOS privacy policy:",
    'hosting_4': "IONOS is used on the basis of Art. 6 para. 1 lit. f GDPR. We have a legitimate interest in displaying our website as reliably as possible. If a corresponding consent has been requested, the processing is carried out exclusively on the basis of Art. 6 para. 1 lit. a GDPR and § 25 para. 1 TTDSG, insofar as the consent includes the storage of cookies or access to information in the user's terminal device (e.g. device fingerprinting) within the meaning of the TTDSG. Consent can be revoked at any time.",
    'general': '3 General notes and mandatory information',
    'general_1': 'Data protection',
    'general_1_1': 'The operators of these pages take the protection of your personal data very seriously. We treat your personal data confidentially and in accordance with the statutory data protection regulations and this privacy policy. When you use this website, various personal data is collected. Personal data is data that can be used to identify you personally. This privacy policy explains what data we collect and what we use it for. It also explains how and for what purpose this is done. We would like to point out that data transmission over the Internet (e.g. when communicating by email) may be subject to security vulnerabilities. Complete protection of data against access by third parties is not possible.',
    'general_2': 'Note on the responsible body',
    'general_2_1': 'The controller responsible for data processing on this website is',
    'general_name': 'Narendrasingham Yokendren',
    'general_2_2': 'The controller is the natural or legal person who alone or jointly with others determines the purposes and means of the processing of personal data (e.g. names, email addresses, etc.).',
    'storage': 'Storage duration',
    'storage_1': 'Unless a more specific storage period has been specified in this privacy policy, your personal data will remain with us until the purpose for data processing no longer applies. If you assert a justified request for deletion or revoke your consent to data processing, your data will be deleted unless we have other legally permissible reasons for storing your personal data (e.g. retention periods under tax or commercial law); in the latter case, the deletion will take place after these reasons no longer apply.',
    'general_3': 'General information on the legal basis for data processing on this website',
    'general_3_1': 'If you have consented to data processing, we process your personal data on the basis of Art. 6 para. 1 lit. a GDPR or Art. 9 para. 2 lit. a GDPR, insofar as special categories of data are processed in accordance with Art. 9 para. 1 GDPR. In the event of express consent to the transfer of personal data to third countries, data processing is also carried out on the basis of Art. 49 para. 1 lit. a GDPR. If you have consented to the storage of cookies or access to information in your end device (e.g. via device fingerprinting), the data processing is also carried out on the basis of Section 25 (1) TTDSG. Consent can be revoked at any time. If your data is required to fulfill the contract or to carry out pre-contractual measures, we process your data on the basis of Art. 6 para. 1 lit. b GDPR. Furthermore, we process your data if this is necessary to fulfill a legal obligation on the basis of Art. 6 para. 1 lit. c GDPR. Data processing may also be carried out on the basis of our legitimate interest in accordance with Art. 6 para. 1 lit. f GDPR. Information on the relevant legal bases in each individual case is provided in the following paragraphs of this privacy policy.',
    'general_4': 'Recipients of personal data',
    'general_4_1': "As part of our business activities, we work together with various external bodies. In some cases, it is also necessary to transfer personal data to these external bodies. We only pass on personal data to external bodies if this is necessary for the fulfillment of a contract, if we are legally obliged to do so (e.g. passing on data to tax authorities), if we have a legitimate interest in the transfer in accordance with Art. 6 para. 1 lit. f GDPR or if another legal basis permits the transfer of data. When using processors, we only pass on our customers' personal data on the basis of a valid contract for order processing. In the case of joint processing, a joint processing agreement is concluded.",
    'general_5': 'Revocation of your consent to data processing',
    'general_5_1': 'Many data processing operations are only possible with your express consent. You can withdraw your consent at any time. The legality of the data processing carried out until the revocation remains unaffected by the revocation.',
    'general_6': 'Right to object to the collection of data in special cases and to direct marketing (Art. 21 GDPR)',
    'general_6_1': 'IF THE DATA PROCESSING IS BASED ON ART. 6 ABS. 1 LIT. E OR F GDPR, YOU HAVE THE RIGHT TO OBJECT TO THE PROCESSING OF YOUR PERSONAL DATA AT ANY TIME ON GROUNDS RELATING TO YOUR PARTICULAR SITUATION; THIS ALSO APPLIES TO PROFILING BASED ON THESE PROVISIONS. THE RESPECTIVE LEGAL BASIS ON WHICH PROCESSING IS BASED CAN BE FOUND IN THIS PRIVACY POLICY. IF YOU OBJECT, WE WILL NO LONGER PROCESS YOUR PERSONAL DATA CONCERNED UNLESS WE CAN DEMONSTRATE COMPELLING LEGITIMATE GROUNDS FOR THE PROCESSING WHICH OVERRIDE YOUR INTERESTS, RIGHTS AND FREEDOMS OR THE PROCESSING SERVES THE ESTABLISHMENT, EXERCISE OR DEFENSE OF LEGAL CLAIMS (OBJECTION PURSUANT TO ART. 21 PARA. 1 GDPR). IF YOUR PERSONAL DATA ARE PROCESSED FOR THE PURPOSE OF DIRECT MARKETING, YOU HAVE THE RIGHT TO OBJECT AT ANY TIME TO THE PROCESSING OF PERSONAL DATA CONCERNING YOU FOR THE PURPOSE OF SUCH MARKETING; THIS ALSO APPLIES TO PROFILING TO THE EXTENT THAT IT IS RELATED TO SUCH DIRECT MARKETING. IF YOU OBJECT, YOUR PERSONAL DATA WILL SUBSEQUENTLY NO LONGER BE WILL SUBSEQUENTLY NO LONGER BE USED FOR THE PURPOSE OF DIRECT MARKETING (OBJECTION PURSUANT TO ART. 21 PARA. 2 GDPR).',
    'general_7': 'Right to lodge a complaint with the competent supervisory authority',
    'general_7_1': 'In the event of breaches of the GDPR, data subjects have the right to lodge a complaint with a supervisory authority, in particular in the Member State of their habitual residence, place of work or place of the alleged infringement. The right to lodge a complaint is without prejudice to other administrative or judicial remedies.',
    'general_8' : 'Right to data portability',
    'general_8_1': 'You have the right to have data that we process automatically on the basis of your consent or in fulfillment of a contract handed over to you or to a third party in a common, machine-readable format. If you request the direct transfer of the data to another controller, this will only take place if it is technically feasible.',
    'general_9': 'Information, correction and deletion',
    'general_9_1': 'Within the framework of the applicable legal provisions, you have the right to free information about your stored personal data, its origin and recipients and the purpose of the data processing and, if necessary, a right to correction or deletion of this data at any time. You can contact us at any time if you have further questions on the subject of personal data.',
    'general_10': 'Right to restriction of processing',
    'general_10_1': 'You have the right to request the restriction of the processing of your personal data. You can contact us at any time to do this. The right to restriction of processing exists in the following cases:',
    'general_10_2_1' : "If you dispute the accuracy of your personal data stored by us, we generally need time to check this. You have the right to request the restriction of the processing of your personal data for the duration of the review. If the processing of your personal data was/is carried out unlawfully, you can request the restriction of data processing instead of erasure. If we no longer need your personal data, but you need it for the exercise, defense or assertion of legal claims, you have the right to request the restriction of the processing of your personal data instead of deletion. If you have lodged an objection pursuant to Art. 21 (1) GDPR, a balance must be struck between your interests and ours. As long as it has not yet been determined whose interests prevail, you have the right to request the restriction of the processing of your personal data.",
    'general_10_2_2': 'If the processing of your personal data was/is carried out unlawfully, you can request the restriction of data processing instead of erasure.',
    'general_10_2_3': 'If we no longer need your personal data, but you need it for the exercise, defense or assertion of legal claims, you have the right to request the restriction of the processing of your personal data instead of deletion.',
    'general_10_2_4': 'If you have lodged an objection pursuant to Art. 21 (1) GDPR, a balance must be struck between your interests and ours. As long as it has not yet been determined whose interests prevail, you have the right to request the restriction of the processing of your personal data.',
    
    'general_10_3': 'If you have restricted the processing of your personal data, this data - apart from its storage - may only be processed with your consent or for the establishment, exercise or defense of legal claims or for the protection of the rights of another natural or legal person or for reasons of important public interest of the European Union or of a Member State.',
    'general_10_4': 'SSL and TLS encryption',
    'general_10_4_1': 'This site uses SSL or TLS encryption for security reasons and to protect the transmission of confidential content, such as orders or inquiries that you send to us as the site operator. You can recognize an encrypted connection by the fact that the address line of the browser changes from "http://" to "https://" and by the lock symbol in your browser line. If SSL or TLS encryption is activated, the data you transmit to us cannot be read by third parties.',
    
    'general_11': '4. data collection on this website',
    'general_11_0': 'Cookies',
    'general_11_1': "Cookies Our websites use so-called “cookies”. Cookies are small data packages and do not cause any damage to your device. They are stored on your device either temporarily for the duration of a session (session cookies) or permanently (persistent cookies). Session cookies are automatically deleted at the end of your visit. Permanent cookies remain stored on your device until you delete them yourself or your web browser automatically deletes them.",
    'general_11_2': 'Cookies can come from us (first-party cookies) or from third-party companies (so-called third-party cookies). Third-party cookies enable the integration of certain services from third-party companies within websites (e.g. cookies for processing payment services). Cookies have various functions. Numerous cookies are technically necessary because certain website functions would not work without them (e.g. the shopping cart function or the display of videos). Other cookies can be used to evaluate user behavior or for advertising purposes.',
    'general_11_3': 'Cookies that are necessary to carry out the electronic communication process, to provide certain functions you want (e.g. for the shopping cart function) or to optimize the website (e.g. cookies to measure the web audience) (necessary cookies). stored on the basis of Art. 6 Para. 1 lit. f GDPR, unless another legal basis is stated. The website operator has a legitimate interest in storing necessary cookies for the technically error-free and optimized provision of its services. If consent to the storage of cookies and comparable recognition technologies has been requested, this will be done',
    
    'general_12': '5. Social media',
    'general_12_1': 'Instagram',
    'general_12_2': 'Functions of the Instagram service are integrated into this website. These functions are offered by Meta Platforms Ireland Limited, 4 Grand Canal Square, Grand Canal Harbour, Dublin 2, Ireland. If the social media element is active, a direct connection is established between your device and the Instagram server. Instagram thereby receives information about your visit to this website. If you are logged into your Instagram account, you can link the content of this website to your Instagram profile by clicking on the Instagram button. This allows Instagram to assign your visit to this website to your user account. We would like to point out that as the provider of the pages, we have no knowledge of the content of the transmitted data or its use by Instagram. The use of this service is based on your consent in accordance with Article 6 Paragraph 1 Letter a GDPR and Section 25 Paragraph 1 TTDSG. Consent can be revoked at any time. To the extent that personal data is collected on our website using the tool described here and forwarded to Facebook or Instagram, we and Meta Platforms Ireland Limited, 4 Grand Canal Square, Grand Canal Harbour, Dublin 2, Ireland are jointly responsible for this data processing ( Art. 26 GDPR). The joint responsibility is limited exclusively to collecting the data and passing it on to Facebook or Instagram. The processing carried out by Facebook or Instagram after forwarding is not part of the shared responsibility. Our joint obligations have been set out in a joint processing agreement.',
    'general_12_3': 'The text of the agreement can be found at:',
    'general_12_4': 'According to this agreement, we are responsible for providing data protection information when using the Facebook or Instagram tool and for the data protection-safe implementation of the tool on our website. Facebook is responsible for the data security of Facebook and Instagram products. You can assert data subject rights (e.g. requests for information) regarding the data processed by Facebook or Instagram directly on Facebook. If those affected assert their rights with us, we are obliged to forward these to Facebook.',
    'general_12_5': "Data transfer to the USA is based on the EU Commission's standard contractual clauses. Details can be found here:",
    'general_12_6': "Further information can be found in Instagram's privacy policy",
    'general_12_7': 'The company is certified according to the “EU-US Data Privacy Framework” (DPF). The DPF is an agreement between the European Union and the USA that is intended to ensure compliance with European data protection standards when data is processed in the USA. Every DPF certified company undertakes to comply with these data protection standards. Further information on this can be obtained from the provider at the following link:',

    'public': '6. Plugins and Tools',
    'public_1': 'YouTube with extended data protection',
    'public_0': 'This website embeds videos from the YouTube website. The website operator is Google Ireland Limited (“Google”), Gordon House, Barrow Street, Dublin 4, Ireland.',
    'public_2': "When you visit one of these websites on which YouTube is integrated, a connection to YouTube's servers is established. The YouTube server is informed which of our pages you have visited. If you are logged into your YouTube account, you enable YouTube to assign your surfing behavior directly to your personal profile. You can prevent this by logging out of your YouTube account.",
    'public_3': "We use YouTube in extended data protection mode. According to YouTube, videos played in extended data protection mode are not used to personalize browsing on YouTube. Ads that are displayed in extended data protection mode are also not personalized. No cookies are set in extended data protection mode. Instead, so-called local storage elements are stored in the user's browser, which, like cookies, contain personal data and can be used for recognition. Details about the extended data protection mode can be found here:",
    'public_4': "If necessary, further data processing operations may take place after activating a YouTube video are triggered, over which we have no influence. The use of YouTube is in the interest of an attractive presentation of our online offerings. This represents a legitimate interest within the meaning of Art. 6 Para. 1 lit TTDSG, insofar as the consent includes the storage of cookies or access to information on the user's end device (e.g. device fingerprinting) within the meaning of the TTDSG. Consent can be revoked at any time.",
    'public_5': "Further information about data protection at YouTube can be found in their data protection declaration at: https://policies.google.com/privacy?hl=de.",
    'public_6': "The company is certified according to the “EU-US Data Privacy Framework” (DPF). The DPF is an agreement between the European Union and the USA that is intended to ensure compliance with European data protection standards when data is processed in the USA. Every DPF certified company undertakes to comply with these data protection standards. Further information on this can be obtained from the provider at the following link: https://www.dataprivacyframework.gov/s/participant-search/participant-detail?contact=true&id=a2zt000000001L5AAI&status=Active",
    'public_7': "Google Fonts (local hosting)",
    'public_8': "This site uses so-called Google Fonts, which are provided by Google, for the uniform display of fonts. The Google Fonts are installed locally. There is no connection to Google servers.",
    'public_9': "Further information about Google Fonts can be found at https://developers.google.com/fonts/faq and in Google's privacy policy: https://policies.google.com/privacy?hl=de."

  };
  content = {
    'en': {
      'products': 'Products',
      'about': 'About us',
      'contact': 'Contact',
      'liv_innovation': 'LIV Innovation',
      'title_sub_1': 'Your partner for innovative automation solutions',
      'title_sub_2': 'Discover how our software can revolutionize your can revolutionize your business.',
      'learn_more': 'Learn More',
      'product_1': 'Innovation',
      'product_1_desc': 'Ready to optimize your business process and increase your productivity? Immerse yourself in the world of automation with LIV Innovation, your expert for tailor-made, innovative software solutions.',
      'product_2': 'Efficiency',
      'product_2_desc': 'In an ever-changing business world, efficiency is the key to success. We offer tailor-made automation solutions to optimize your operational business processes and take your company to the next level.',
      'product_3': 'Integration',
      'product_3_desc': 'Do you want to automate manual processes and integrate them into your existing workflow? At LIV Innovation, we offer automation solutions tailored to your specific needs.',
      'about_us': 'LIV Innovation aims to help companies work smarter and more efficiently. We believe in the power of automation to take over repetitive tasks and free up human resources for creative and strategic challenges.',
      'vision': 'Our Vision & Mission',
      'vision_mission': 'Our vision is to create a world where technology enhances human performance and helps companies achieve their goals.',
      'hello': 'Hello!',
      'love_to_hear': 'We’d love to hear from you.Here’s how you can reach us...',
      'imprint': 'Imprint',
      'data_protection': 'Data protection',
      'address': 'Bornheimer Landwehr 33, 60385 Frankfurt',
      'mobile': 'Phone +49 179 221 1285',
      'mail': 'E-mail: info@liv-innovation.com',
      'imprint_content_1': 'Sales tax identification number according to § 27a UStG: follows...........',
      'liability': 'Limitation of liability:',
      'liability_1': 'Contents of the LIV Innovation website',
      'liability_2': "The content of the LIV Innovation website has been compiled with the greatest possible care. However, LIV Innovation assumes no liability for the accuracy, completeness and timeliness of the content provided. The use of the retrievable content is at the user's own risk.",
      'external': 'External links:',
      'external_1': 'The LIV Innovation website contains links to third-party websites ("external links"). These websites are subject to the liability of the respective operators. When the external links were first created, LIV Innovation checked the third-party content for any legal violations. No legal violations were apparent at that time.',
      'external_2': 'LIV Innovation has no influence whatsoever on the current and future design and content of the linked pages. LIV Innovation therefore expressly distances itself from any illegal or immoral content on the linked pages.',
      'external_3': 'For illegal, incorrect or incomplete contents and in particular for damages resulting from the use or non-use of the information offered via the link, the provider of the page to which reference is made is solely liable, but not LIV Innovation, which merely refers to the publication by setting the link.',
      'external_4': 'The inclusion of external links does not mean that LIV Innovation adopts the content behind the reference or link as its own. LIV Innovation cannot reasonably be expected to constantly monitor these external links without concrete evidence of legal violations. However, such external links will be deleted immediately if we become aware of any legal violations.',
      'privacy': 'Privacy policy',
      'privacy_1': '1. Data protection at a glance',
      'privacy_1_1': 'General information',
      'privacy_1_2': 'The following information provides a simple overview of what happens to your personal data when you visit this website. Personal data is any data that can be used to identify you personally. Detailed information on the subject of data protection can be found in our data protection declaration listed below this text.',
      'privacy_1_3': 'Data collection on this website',
      'privacy_1_4': 'Who is responsible for data collection on this website?',
      'privacy_1_5': 'Data processing on this website is carried out by the website operator. You can find their contact details in the "Information on the controller" section of this privacy policy.',
      'privacy_1_6': 'How do we collect your data?',
      'privacy_1_7': 'On the one hand, your data is collected when you provide it to us. This may, for example, be data that you enter in a contact form.',
      'privacy_1_8': 'Other data is collected automatically or with your consent by our IT systems when you visit the website. This is primarily technical data (e.g. internet browser, operating system or time of page view). This data is collected automatically as soon as you enter this website.',
      'privacy_1_9': 'What do we use your data for?',
      'privacy_1_10': 'Some of the data is collected to ensure that the website is provided without errors. Other data may be used to analyze your user behavior.',
      'privacy_1_11': 'What rights do you have regarding your data?',
      'privacy_1_12': 'You have the right to receive information about the origin, recipient and purpose of your stored personal data free of charge at any time. You also have the right to request the correction or deletion of this data. If you have given your consent to data processing, you can revoke this consent at any time for the future. You also have the right to request the restriction of the processing of your personal data under certain circumstances. You also have the right to lodge a complaint with the competent supervisory authority.',
      'privacy_1_13': 'You can contact us at any time if you have further questions on the subject of data protection.',
      'privacy_1_14': 'Analysis tools and tools from third-party providers',
      'privacy_1_15': 'When you visit this website, your surfing behavior may be statistically evaluated. This is mainly done with so-called analysis programs.',
      'privacy_1_16': 'Detailed information on these analysis programs can be found in the following privacy policy.',
      'hosting': '2. Hosting',
      'hosting_1': 'We host the content of our website with the following provider:',
      'hosting_2': 'IONOS',
      'hosting_3': "The provider is IONOS SE, Elgendorfer Str. 57, 56410 Montabaur (hereinafter referred to as IONOS). When you visit our website, IONOS collects various log files including your IP addresses. Details can be found in the IONOS privacy policy:",
      'hosting_4': "IONOS is used on the basis of Art. 6 para. 1 lit. f GDPR. We have a legitimate interest in displaying our website as reliably as possible. If a corresponding consent has been requested, the processing is carried out exclusively on the basis of Art. 6 para. 1 lit. a GDPR and § 25 para. 1 TTDSG, insofar as the consent includes the storage of cookies or access to information in the user's terminal device (e.g. device fingerprinting) within the meaning of the TTDSG. Consent can be revoked at any time.",
      'general': '3 General notes and mandatory information',
      'general_1': 'Data protection',
      'general_1_1': 'The operators of these pages take the protection of your personal data very seriously. We treat your personal data confidentially and in accordance with the statutory data protection regulations and this privacy policy. When you use this website, various personal data is collected. Personal data is data that can be used to identify you personally. This privacy policy explains what data we collect and what we use it for. It also explains how and for what purpose this is done. We would like to point out that data transmission over the Internet (e.g. when communicating by email) may be subject to security vulnerabilities. Complete protection of data against access by third parties is not possible.',
      'general_2': 'Note on the responsible body',
      'general_2_1': 'The controller responsible for data processing on this website is',
      'general_name': 'Narendrasingham Yokendren',
      'general_2_2': 'The controller is the natural or legal person who alone or jointly with others determines the purposes and means of the processing of personal data (e.g. names, email addresses, etc.).',
      'storage': 'Storage duration',
      'storage_1': 'Unless a more specific storage period has been specified in this privacy policy, your personal data will remain with us until the purpose for data processing no longer applies. If you assert a justified request for deletion or revoke your consent to data processing, your data will be deleted unless we have other legally permissible reasons for storing your personal data (e.g. retention periods under tax or commercial law); in the latter case, the deletion will take place after these reasons no longer apply.',
      'general_3': 'General information on the legal basis for data processing on this website',
      'general_3_1': 'If you have consented to data processing, we process your personal data on the basis of Art. 6 para. 1 lit. a GDPR or Art. 9 para. 2 lit. a GDPR, insofar as special categories of data are processed in accordance with Art. 9 para. 1 GDPR. In the event of express consent to the transfer of personal data to third countries, data processing is also carried out on the basis of Art. 49 para. 1 lit. a GDPR. If you have consented to the storage of cookies or access to information in your end device (e.g. via device fingerprinting), the data processing is also carried out on the basis of Section 25 (1) TTDSG. Consent can be revoked at any time. If your data is required to fulfill the contract or to carry out pre-contractual measures, we process your data on the basis of Art. 6 para. 1 lit. b GDPR. Furthermore, we process your data if this is necessary to fulfill a legal obligation on the basis of Art. 6 para. 1 lit. c GDPR. Data processing may also be carried out on the basis of our legitimate interest in accordance with Art. 6 para. 1 lit. f GDPR. Information on the relevant legal bases in each individual case is provided in the following paragraphs of this privacy policy.',
      'general_4': 'Recipients of personal data',
      'general_4_1': "As part of our business activities, we work together with various external bodies. In some cases, it is also necessary to transfer personal data to these external bodies. We only pass on personal data to external bodies if this is necessary for the fulfillment of a contract, if we are legally obliged to do so (e.g. passing on data to tax authorities), if we have a legitimate interest in the transfer in accordance with Art. 6 para. 1 lit. f GDPR or if another legal basis permits the transfer of data. When using processors, we only pass on our customers' personal data on the basis of a valid contract for order processing. In the case of joint processing, a joint processing agreement is concluded.",
      'general_5': 'Revocation of your consent to data processing',
      'general_5_1': 'Many data processing operations are only possible with your express consent. You can withdraw your consent at any time. The legality of the data processing carried out until the revocation remains unaffected by the revocation.',
      'general_6': 'Right to object to the collection of data in special cases and to direct marketing (Art. 21 GDPR)',
      'general_6_1': 'IF THE DATA PROCESSING IS BASED ON ART. 6 ABS. 1 LIT. E OR F GDPR, YOU HAVE THE RIGHT TO OBJECT TO THE PROCESSING OF YOUR PERSONAL DATA AT ANY TIME ON GROUNDS RELATING TO YOUR PARTICULAR SITUATION; THIS ALSO APPLIES TO PROFILING BASED ON THESE PROVISIONS. THE RESPECTIVE LEGAL BASIS ON WHICH PROCESSING IS BASED CAN BE FOUND IN THIS PRIVACY POLICY. IF YOU OBJECT, WE WILL NO LONGER PROCESS YOUR PERSONAL DATA CONCERNED UNLESS WE CAN DEMONSTRATE COMPELLING LEGITIMATE GROUNDS FOR THE PROCESSING WHICH OVERRIDE YOUR INTERESTS, RIGHTS AND FREEDOMS OR THE PROCESSING SERVES THE ESTABLISHMENT, EXERCISE OR DEFENSE OF LEGAL CLAIMS (OBJECTION PURSUANT TO ART. 21 PARA. 1 GDPR). IF YOUR PERSONAL DATA ARE PROCESSED FOR THE PURPOSE OF DIRECT MARKETING, YOU HAVE THE RIGHT TO OBJECT AT ANY TIME TO THE PROCESSING OF PERSONAL DATA CONCERNING YOU FOR THE PURPOSE OF SUCH MARKETING; THIS ALSO APPLIES TO PROFILING TO THE EXTENT THAT IT IS RELATED TO SUCH DIRECT MARKETING. IF YOU OBJECT, YOUR PERSONAL DATA WILL SUBSEQUENTLY NO LONGER BE WILL SUBSEQUENTLY NO LONGER BE USED FOR THE PURPOSE OF DIRECT MARKETING (OBJECTION PURSUANT TO ART. 21 PARA. 2 GDPR).',
      'general_7': 'Right to lodge a complaint with the competent supervisory authority',
      'general_7_1': 'In the event of breaches of the GDPR, data subjects have the right to lodge a complaint with a supervisory authority, in particular in the Member State of their habitual residence, place of work or place of the alleged infringement. The right to lodge a complaint is without prejudice to other administrative or judicial remedies.',
      'general_8' : 'Right to data portability',
      'general_8_1': 'You have the right to have data that we process automatically on the basis of your consent or in fulfillment of a contract handed over to you or to a third party in a common, machine-readable format. If you request the direct transfer of the data to another controller, this will only take place if it is technically feasible.',
      'general_9': 'Information, correction and deletion',
      'general_9_1': 'Within the framework of the applicable legal provisions, you have the right to free information about your stored personal data, its origin and recipients and the purpose of the data processing and, if necessary, a right to correction or deletion of this data at any time. You can contact us at any time if you have further questions on the subject of personal data.',
      'general_10': 'Right to restriction of processing',
      'general_10_1': 'You have the right to request the restriction of the processing of your personal data. You can contact us at any time to do this. The right to restriction of processing exists in the following cases:',
      'general_10_2_1' : "If you dispute the accuracy of your personal data stored by us, we generally need time to check this. You have the right to request the restriction of the processing of your personal data for the duration of the review. If the processing of your personal data was/is carried out unlawfully, you can request the restriction of data processing instead of erasure. If we no longer need your personal data, but you need it for the exercise, defense or assertion of legal claims, you have the right to request the restriction of the processing of your personal data instead of deletion. If you have lodged an objection pursuant to Art. 21 (1) GDPR, a balance must be struck between your interests and ours. As long as it has not yet been determined whose interests prevail, you have the right to request the restriction of the processing of your personal data.",
      'general_10_2_2': 'If the processing of your personal data was/is carried out unlawfully, you can request the restriction of data processing instead of erasure.',
      'general_10_2_3': 'If we no longer need your personal data, but you need it for the exercise, defense or assertion of legal claims, you have the right to request the restriction of the processing of your personal data instead of deletion.',
      'general_10_2_4': 'If you have lodged an objection pursuant to Art. 21 (1) GDPR, a balance must be struck between your interests and ours. As long as it has not yet been determined whose interests prevail, you have the right to request the restriction of the processing of your personal data.',
      
      'general_10_3': 'If you have restricted the processing of your personal data, this data - apart from its storage - may only be processed with your consent or for the establishment, exercise or defense of legal claims or for the protection of the rights of another natural or legal person or for reasons of important public interest of the European Union or of a Member State.',
      'general_10_4': 'SSL and TLS encryption',
      'general_10_4_1': 'This site uses SSL or TLS encryption for security reasons and to protect the transmission of confidential content, such as orders or inquiries that you send to us as the site operator. You can recognize an encrypted connection by the fact that the address line of the browser changes from "http://" to "https://" and by the lock symbol in your browser line. If SSL or TLS encryption is activated, the data you transmit to us cannot be read by third parties.',
      
      'general_11': '4. Data collection on this website',
      'general_11_0': 'Cookies',
      'general_11_1': "Cookies Our websites use so-called “cookies”. Cookies are small data packages and do not cause any damage to your device. They are stored on your device either temporarily for the duration of a session (session cookies) or permanently (persistent cookies). Session cookies are automatically deleted at the end of your visit. Permanent cookies remain stored on your device until you delete them yourself or your web browser automatically deletes them.",
      'general_11_2': 'Cookies can come from us (first-party cookies) or from third-party companies (so-called third-party cookies). Third-party cookies enable the integration of certain services from third-party companies within websites (e.g. cookies for processing payment services). Cookies have various functions. Numerous cookies are technically necessary because certain website functions would not work without them (e.g. the shopping cart function or the display of videos). Other cookies can be used to evaluate user behavior or for advertising purposes.',
      'general_11_3': 'Cookies that are necessary to carry out the electronic communication process, to provide certain functions you want (e.g. for the shopping cart function) or to optimize the website (e.g. cookies to measure the web audience) (necessary cookies). stored on the basis of Art. 6 Para. 1 lit. f GDPR, unless another legal basis is stated. The website operator has a legitimate interest in storing necessary cookies for the technically error-free and optimized provision of its services. If consent to the storage of cookies and comparable recognition technologies has been requested, this will be done',
      
      'general_12': '5. Social media',
      'general_12_1': 'Instagram',
      'general_12_2': 'Functions of the Instagram service are integrated into this website. These functions are offered by Meta Platforms Ireland Limited, 4 Grand Canal Square, Grand Canal Harbour, Dublin 2, Ireland. If the social media element is active, a direct connection is established between your device and the Instagram server. Instagram thereby receives information about your visit to this website. If you are logged into your Instagram account, you can link the content of this website to your Instagram profile by clicking on the Instagram button. This allows Instagram to assign your visit to this website to your user account. We would like to point out that as the provider of the pages, we have no knowledge of the content of the transmitted data or its use by Instagram. The use of this service is based on your consent in accordance with Article 6 Paragraph 1 Letter a GDPR and Section 25 Paragraph 1 TTDSG. Consent can be revoked at any time. To the extent that personal data is collected on our website using the tool described here and forwarded to Facebook or Instagram, we and Meta Platforms Ireland Limited, 4 Grand Canal Square, Grand Canal Harbour, Dublin 2, Ireland are jointly responsible for this data processing ( Art. 26 GDPR). The joint responsibility is limited exclusively to collecting the data and passing it on to Facebook or Instagram. The processing carried out by Facebook or Instagram after forwarding is not part of the shared responsibility. Our joint obligations have been set out in a joint processing agreement.',
      'general_12_3': 'The text of the agreement can be found at: https://www.facebook.com/legal/controller_addendum.',
      'general_12_4': 'According to this agreement, we are responsible for providing data protection information when using the Facebook or Instagram tool and for the data protection-safe implementation of the tool on our website. Facebook is responsible for the data security of Facebook and Instagram products. You can assert data subject rights (e.g. requests for information) regarding the data processed by Facebook or Instagram directly on Facebook. If those affected assert their rights with us, we are obliged to forward these to Facebook.',
      'general_12_5': "Data transfer to the USA is based on the EU Commission's standard contractual clauses. Details can be found here:",
      'general_12_6': "Further information can be found in Instagram's privacy policy",
      'general_12_7': 'The company is certified according to the “EU-US Data Privacy Framework” (DPF). The DPF is an agreement between the European Union and the USA that is intended to ensure compliance with European data protection standards when data is processed in the USA. Every DPF certified company undertakes to comply with these data protection standards. Further information on this can be obtained from the provider at the following link:',

      'public': '6. Plugins and Tools',
      'public_1': 'YouTube with extended data protection',
      'public_0': 'This website embeds videos from the YouTube website. The website operator is Google Ireland Limited (“Google”), Gordon House, Barrow Street, Dublin 4, Ireland.',
      'public_2': "When you visit one of these websites on which YouTube is integrated, a connection to YouTube's servers is established. The YouTube server is informed which of our pages you have visited. If you are logged into your YouTube account, you enable YouTube to assign your surfing behavior directly to your personal profile. You can prevent this by logging out of your YouTube account.",
      'public_3': "We use YouTube in extended data protection mode. According to YouTube, videos played in extended data protection mode are not used to personalize browsing on YouTube. Ads that are displayed in extended data protection mode are also not personalized. No cookies are set in extended data protection mode. Instead, so-called local storage elements are stored in the user's browser, which, like cookies, contain personal data and can be used for recognition. Details about the extended data protection mode can be found here:",
      'public_4': "If necessary, further data processing operations may take place after activating a YouTube video are triggered, over which we have no influence. The use of YouTube is in the interest of an attractive presentation of our online offerings. This represents a legitimate interest within the meaning of Art. 6 Para. 1 lit TTDSG, insofar as the consent includes the storage of cookies or access to information on the user's end device (e.g. device fingerprinting) within the meaning of the TTDSG. Consent can be revoked at any time.",
      'public_5': "Further information about data protection at YouTube can be found in their data protection declaration at:",
      'public_6': "The company is certified according to the “EU-US Data Privacy Framework” (DPF). The DPF is an agreement between the European Union and the USA that is intended to ensure compliance with European data protection standards when data is processed in the USA. Every DPF certified company undertakes to comply with these data protection standards. Further information on this can be obtained from the provider at the following link:",
      'public_7': "Google Fonts (local hosting)",
      'public_8': "This site uses so-called Google Fonts, which are provided by Google, for the uniform display of fonts. The Google Fonts are installed locally. There is no connection to Google servers.",
      'public_9': "Further information about Google Fonts can be found at https://developers.google.com/fonts/faq and in Google's privacy policy:"


    },
    'ge': {
      'products': 'Products',
      'about': 'Über uns',
      'contact': 'Kontakt',
      'liv_innovation': 'LIV Innovation',
      'title_sub_1': 'Ihrem Partner für innovative Automatisierungslösungen',
      'title_sub_2': 'Entdecken Sie, wie unsere Software Ihr Unternehmen revolutionieren kann.',
      'learn_more': 'Mehr erfahren',
      'product_1': 'Innovation',
      'product_1_desc': 'Bereit, Ihren Geschäftsprozess zu optimieren und Ihre Produktivität zu steigern? Tauchen Sie ein in die Welt der Automatisierung mit LIV Innovation, Ihrem Experten für maßgeschneiderte, innovative  Softwarelösungen.',
      'product_2': 'Effizienz',
      'product_2_desc': 'In einer sich ständig wandelnden Geschäftswelt ist Effizienz der Schlüssel zum Erfolg. Bei uns bieten wir maßgeschneiderte Automatisierungslösungen, um Ihre operative Geschäftsprozesse zu optimieren und Ihr Unternehmen auf die nächste Stufe zu heben.',
      'product_3': 'Integration',
      'product_3_desc': 'Möchten Sie manuelle Prozesse automatisieren und in Ihren bisherigen Ablauf integrieren? Bei LIV Innovation bieten wir Automatisierungslösungen, die auf Ihre spezifischen Anforderungen zugeschnitten sind.',
      'about_us': 'LIV Innovation möchte Unternehmen dabei unterstützen, intelligenter und effizienter zu arbeiten. Wir glauben an die Kraft der Automatisierung, um repetitive Aufgaben zu übernehmen und menschliche Ressourcen für kreative und strategische Herausforderungen freizusetzen.',
      'vision': 'Our Vision & Mission',
      'vision_mission': 'Unsere Vision ist es, eine Welt zu schaffen, in der Technologie die menschliche Leistungsfähigkeit erweitert und Unternehmen dabei hilft, ihre Ziele zu erreichen.',
      'hello': 'Hallo!',
      'love_to_hear': 'Wir würden uns freuen, von Ihnen zu hören. Hier erfahren Sie, wie Sie uns erreichen können...',
      'imprint': 'Impressum',
      'data_protection': 'Datenschutz',
      'address': 'Bornheimer Landwehr 33, 60385 Frankfurt',
      'mobile': 'Telefon: +49 179 221 1285',
      'mail': 'E-mail: info@liv-innovation.com',
      'imprint_content_1': 'Umsatzsteueridentifikationsnummer nach § 27a UStG: folgt………..',
      'liability': 'Haftungsbeschränkung:',
      'liability_1': 'Inhalte der Internet-Präsenz der LIV Innovation',
      'liability_2': "Die Inhalte der Internet-Präsenz der  LIV Innovation werden mit größtmöglicher Sorgfalt erstellt. Die LIV Innovation übernimmt jedoch keine Gewähr für die Richtigkeit, Vollständigkeit und Aktualität der bereitgestellten Inhalte. Die Nutzung der abrufbaren Inhalte erfolgt auf eigene Gefahr des Nutzers.",
      'external': 'Externe links:',
      'external_1': 'Die Internet-Präsenz der LIV Innovation enthält Verknüpfungen zu Internet-Seiten Dritter („externe Links“). Diese Internet-Seiten unterliegen der Haftung der jeweiligen Betreiber. Die LIV Innovation hat bei der erstmaligen Verknüpfung der externen Links die fremden Inhalte daraufhin überprüft, ob etwaige Rechtsverstöße bestehen. Zu dem Zeitpunkt waren keine Rechtsverstöße ersichtlich.',
      'external_2': 'Die LIV Innovation hat keinerlei Einfluss auf die aktuelle und zukünftige Gestaltung und auf die Inhalte der verknüpften Seiten. Die LIV Innovation distanziert sich daher ausdrücklich von illegalen oder gegen die guten Sitten verstoßenden Inhalten der verlinkten Seiten.',
      'external_3': 'Für illegale, fehlerhafte oder unvollständige Inhalte und insbesondere für Schäden, die aus der Nutzung oder Nichtnutzung der über die Verlinkung angebotenen Informationen entstehen, haftet alleine der Anbieter der Seite, auf die verwiesen wurde, nicht jedoch die LIV Innovation, die durch die Linksetzung lediglich auf die Veröffentlichung verweist.',
      'external_4': 'Das Setzen von externen Links bedeutet nicht, dass sich die LIV Innovation die hinter dem Verweis oder Link liegenden Inhalte zu Eigen macht. Eine ständige Kontrolle dieser externen Links ist für die LIV Innovation ohne konkrete Hinweise auf Rechtsverstöße nicht zumutbar. Bei Kenntnis von Rechtsverstößen werden jedoch derartige externe Links unverzüglich gelöscht.',
      

      'privacy': 'Datenschutzerklärung',
      'privacy_1': '1. Datenschutz auf einen Blick',
      'privacy_1_1': 'Allgemeine Hinweise',
      'privacy_1_2': 'Die folgenden Hinweise geben einen einfachen Überblick darüber, was mit Ihren personenbezogenen Daten passiert, wenn Sie diese Website besuchen. Personenbezogene Daten sind alle Daten, mit denen Sie persönlich identifiziert werden können. Ausführliche Informationen zum Thema Datenschutz entnehmen Sie unserer unter diesem Text aufgeführten Datenschutzerklärung.',
      'privacy_1_3': 'Datenerfassung auf dieser Website',
      'privacy_1_4': 'Wer ist verantwortlich für die Datenerfassung auf dieser Website?',
      'privacy_1_5': 'Die Datenverarbeitung auf dieser Website erfolgt durch den Websitebetreiber. Dessen Kontaktdaten können Sie dem Abschnitt „Hinweis zur Verantwortlichen Stelle“ in dieser Datenschutzerklärung entnehmen.',
      'privacy_1_6': 'Wie erfassen wir Ihre Daten?',
      'privacy_1_7': 'Ihre Daten werden zum einen dadurch erhoben, dass Sie uns diese mitteilen. Hierbei kann es sich z. B. um Daten handeln, die Sie in ein Kontaktformular eingeben.',
      'privacy_1_8': 'Andere Daten werden automatisch oder nach Ihrer Einwilligung beim Besuch der Website durch unsere IT- Systeme erfasst. Das sind vor allem technische Daten (z. B. Internetbrowser, Betriebssystem oder Uhrzeit des Seitenaufrufs). Die Erfassung dieser Daten erfolgt automatisch, sobald Sie diese Website betreten.',
      'privacy_1_9': 'Wofür nutzen wir Ihre Daten?',
      'privacy_1_10': 'Ein Teil der Daten wird erhoben, um eine fehlerfreie Bereitstellung der Website zu gewährleisten. Andere Daten können zur Analyse Ihres Nutzerverhaltens verwendet werden.',
      'privacy_1_11': 'Welche Rechte haben Sie bezüglich Ihrer Daten?',
      'privacy_1_12': 'Sie haben jederzeit das Recht, unentgeltlich Auskunft über Herkunft, Empfänger und Zweck Ihrer gespeicherten personenbezogenen Daten zu erhalten. Sie haben außerdem ein Recht, die Berichtigung oder Löschung dieser Daten zu verlangen. Wenn Sie eine Einwilligung zur Datenverarbeitung erteilt haben, können Sie diese Einwilligung jederzeit für die Zukunft widerrufen. Außerdem haben Sie das Recht, unter bestimmten Umständen die Einschränkung der Verarbeitung Ihrer personenbezogenen Daten zu verlangen. Des Weiteren steht Ihnen ein Beschwerderecht bei der zuständigen Aufsichtsbehörde zu.',
      'privacy_1_13': 'Hierzu sowie zu weiteren Fragen zum Thema Datenschutz können Sie sich jederzeit an uns wenden.',
      'privacy_1_14': 'Analyse-Tools und Tools von Drittanbietern',
      'privacy_1_15': 'Beim Besuch dieser Website kann Ihr Surf-Verhalten statistisch ausgewertet werden. Das geschieht vor allem mit sogenannten Analyseprogrammen.',
      'privacy_1_16': 'Detaillierte Informationen zu diesen Analyseprogrammen finden Sie in der folgenden Datenschutzerklärung.',
      'hosting': '2. Hosting',
      'hosting_1': 'Wir hosten die Inhalte unserer Website bei folgendem Anbieter:',
      'hosting_2': 'IONOS',
      'hosting_3': "Anbieter ist die IONOS SE, Elgendorfer Str. 57, 56410 Montabaur (nachfolgend IONOS). Wenn Sie unsere Website besuchen, erfasst IONOS verschiedene Logfiles inklusive Ihrer IP-Adressen. Details entnehmen Sie der Datenschutzerklärung von IONOS:",
      'hosting_4': "Die Verwendung von IONOS erfolgt auf Grundlage von Art. 6 Abs. 1 lit. f DSGVO. Wir haben ein berechtigtes Interesse an einer möglichst zuverlässigen Darstellung unserer Website. Sofern eine entsprechende Einwilligung abgefragt wurde, erfolgt die Verarbeitung ausschließlich auf Grundlage von Art. 6 Abs. 1 lit. a DSGVO und § 25 Abs. 1 TTDSG, soweit die Einwilligung die Speicherung von Cookies oder den Zugriff auf Informationen im Endgerät des Nutzers (z. B. Device-Fingerprinting) im Sinne des TTDSG umfasst. Die Einwilligung ist jederzeit widerrufbar.",
      'general': '3. Allgemeine Hinweise und Pflichtinformationen',
      'general_1': 'Datenschutz',
      'general_1_1': 'Die Betreiber dieser Seiten nehmen den Schutz Ihrer persönlichen Daten sehr ernst. Wir behandeln Ihre personenbezogenen Daten vertraulich und entsprechend den gesetzlichen Datenschutzvorschriften sowie dieser Datenschutzerklärung. Wenn Sie diese Website benutzen, werden verschiedene personenbezogene Daten erhoben. Personenbezogene Daten sind Daten, mit denen Sie persönlich identifiziert werden können. Die vorliegende Datenschutzerklärung erläutert, welche Daten wir erheben und wofür wir sie nutzen. Sie erläutert auch, wie und zu welchem Zweck das geschieht. Wir weisen darauf hin, dass die Datenübertragung im Internet (z. B. bei der Kommunikation per E-Mail) Sicherheitslücken aufweisen kann. Ein lückenloser Schutz der Daten vor dem Zugriff durch Dritte ist nicht möglich.',
      'general_2': 'Hinweis zur verantwortlichen Stelle',
      'general_2_1': 'Die verantwortliche Stelle für die Datenverarbeitung auf dieser Website ist:',
      'general_name': 'Narendrasingham Yokendren',
      'general_2_2': 'Verantwortliche Stelle ist die natürliche oder juristische Person, die allein oder gemeinsam mit anderen über die Zwecke und Mittel der Verarbeitung von personenbezogenen Daten (z. B. Namen, E-Mail-Adressen o. Ä.) entscheidet.',
      'storage': 'Speicherdauer',
      'storage_1': 'Soweit innerhalb dieser Datenschutzerklärung keine speziellere Speicherdauer genannt wurde, verbleiben Ihre personenbezogenen Daten bei uns, bis der Zweck für die Datenverarbeitung entfällt. Wenn Sie ein berechtigtes Löschersuchen geltend machen oder eine Einwilligung zur Datenverarbeitung widerrufen, werden Ihre Daten gelöscht, sofern wir keine anderen rechtlich zulässigen Gründe für die Speicherung Ihrer personenbezogenen Daten haben (z. B. steuer- oder handelsrechtliche Aufbewahrungsfristen); im letztgenannten Fall erfolgt die Löschung nach Fortfall dieser Gründe.',
      'general_3': 'Allgemeine Hinweise zu den Rechtsgrundlagen der Datenverarbeitung auf dieser Website',
      'general_3_1': 'Sofern Sie in die Datenverarbeitung eingewilligt haben, verarbeiten wir Ihre personenbezogenen Daten auf Grundlage von Art. 6 Abs. 1 lit. a DSGVO bzw. Art. 9 Abs. 2 lit. a DSGVO, sofern besondere Datenkategorien nach Art. 9 Abs. 1 DSGVO verarbeitet werden. Im Falle einer ausdrücklichen Einwilligung in die Übertragung personenbezogener Daten in Drittstaaten erfolgt die Datenverarbeitung außerdem auf Grundlage von Art. 49 Abs. 1 lit. a DSGVO. Sofern Sie in die Speicherung von Cookies oder in den Zugriff auf Informationen in Ihr Endgerät (z. B. via Device-Fingerprinting) eingewilligt haben, erfolgt die Datenverarbeitung zusätzlich auf Grundlage von § 25 Abs. 1 TTDSG. Die Einwilligung ist jederzeit widerrufbar. Sind Ihre Daten zur Vertragserfüllung oder zur Durchführung vorvertraglicher Maßnahmen erforderlich, verarbeiten wir Ihre Daten auf Grundlage des Art. 6 Abs. 1 lit. b DSGVO. Des Weiteren verarbeiten wir Ihre Daten, sofern diese zur Erfüllung einer rechtlichen Verpflichtung erforderlich sind auf Grundlage von Art. 6 Abs. 1 lit. c DSGVO. Die Datenverarbeitung kann ferner auf Grundlage unseres berechtigten Interesses nach Art. 6 Abs. 1 lit. f DSGVO erfolgen. Über die jeweils im Einzelfall einschlägigen Rechtsgrundlagen wird in den folgenden Absätzen dieser Datenschutzerklärung informiert.',
      'general_4': 'Empfänger von personenbezogenen Daten',
      'general_4_1': "Im Rahmen unserer Geschäftstätigkeit arbeiten wir mit verschiedenen externen Stellen zusammen. Dabei ist teilweise auch eine Übermittlung von personenbezogenen Daten an diese externen Stellen erforderlich. Wir geben personenbezogene Daten nur dann an externe Stellen weiter, wenn dies im Rahmen einer Vertragserfüllung erforderlich ist, wenn wir gesetzlich hierzu verpflichtet sind (z. B. Weitergabe von Daten an Steuerbehörden), wenn wir ein berechtigtes Interesse nach Art. 6 Abs. 1 lit. f DSGVO an der Weitergabe haben oder wenn eine sonstige Rechtsgrundlage die Datenweitergabe erlaubt. Beim Einsatz von Auftragsverarbeitern geben wir personenbezogene Daten unserer Kunden nur auf Grundlage eines gültigen Vertrags über Auftragsverarbeitung weiter. Im Falle einer gemeinsamen Verarbeitung wird ein Vertrag über gemeinsame Verarbeitung geschlossen.",
      'general_5': 'Widerruf Ihrer Einwilligung zur Datenverarbeitung',
      'general_5_1': 'Viele Datenverarbeitungsvorgänge sind nur mit Ihrer ausdrücklichen Einwilligung möglich. Sie können eine bereits erteilte Einwilligung jederzeit widerrufen. Die Rechtmäßigkeit der bis zum Widerruf erfolgten Datenverarbeitung bleibt vom Widerruf unberührt.',
      'general_6': 'Widerspruchsrecht gegen die Datenerhebung in besonderen Fällen sowie gegen Direktwerbung (Art. 21 DSGVO)',
      'general_6_1': 'WENN DIE DATENVERARBEITUNG AUF GRUNDLAGE VON ART. 6 ABS. 1 LIT. E ODER F DSGVO ERFOLGT, HABEN SIE JEDERZEIT DAS RECHT, AUS GRÜNDEN, DIE SICH AUS IHRER BESONDEREN SITUATION ERGEBEN, GEGEN DIE VERARBEITUNG IHRER PERSONENBEZOGENEN DATEN WIDERSPRUCH EINZULEGEN; DIES GILT AUCH FÜR EIN AUF DIESE BESTIMMUNGEN GESTÜTZTES PROFILING. DIE JEWEILIGE RECHTSGRUNDLAGE, AUF DENEN EINE VERARBEITUNG BERUHT, ENTNEHMEN SIE DIESER DATENSCHUTZERKLÄRUNG. WENN SIE WIDERSPRUCH EINLEGEN, WERDEN WIR IHRE BETROFFENEN PERSONENBEZOGENEN DATEN NICHT MEHR VERARBEITEN, ES SEI DENN, WIR KÖNNEN ZWINGENDE SCHUTZWÜRDIGE GRÜNDE FÜR DIE VERARBEITUNG NACHWEISEN, DIE IHRE INTERESSEN, RECHTE UND FREIHEITEN ÜBERWIEGEN ODER DIE VERARBEITUNG DIENT DER GELTENDMACHUNG, AUSÜBUNG ODER VERTEIDIGUNG VON RECHTSANSPRÜCHEN (WIDERSPRUCH NACH ART. 21 ABS. 1 DSGVO). WERDEN IHRE PERSONENBEZOGENEN DATEN VERARBEITET, UM DIREKTWERBUNG ZU BETREIBEN, SO HABEN SIE DAS RECHT, JEDERZEIT WIDERSPRUCH GEGEN DIE VERARBEITUNG SIE BETREFFENDER PERSONENBEZOGENER DATEN ZUM ZWECKE DERARTIGER WERBUNG EINZULEGEN; DIES GILT AUCH FÜR DAS PROFILING, SOWEIT ES MIT SOLCHER DIREKTWERBUNG IN VERBINDUNG STEHT. WENN SIE WIDERSPRECHEN, WERDEN IHRE PERSONENBEZOGENEN DATEN ANSCHLIESSEND NICHT MEHR ZUM ZWECKE DER DIREKTWERBUNG VERWENDET (WIDERSPRUCH NACH ART. 21 ABS. 2 DSGVO).',
      'general_7': 'Beschwerderecht bei der zuständigen Aufsichtsbehörde',
      'general_7_1': 'Im Falle von Verstößen gegen die DSGVO steht den Betroffenen ein Beschwerderecht bei einer Aufsichtsbehörde, insbesondere in dem Mitgliedstaat ihres gewöhnlichen Aufenthalts, ihres Arbeitsplatzes oder des Orts des mutmaßlichen Verstoßes zu. Das Beschwerderecht besteht unbeschadet anderweitiger verwaltungsrechtlicher oder gerichtlicher Rechtsbehelfe.',
      'general_8' : 'Recht auf Datenübertragbarkeit',
      'general_8_1': 'Sie haben das Recht, Daten, die wir auf Grundlage Ihrer Einwilligung oder in Erfüllung eines Vertrags automatisiert verarbeiten, an sich oder an einen Dritten in einem gängigen, maschinenlesbaren Format aushändigen zu lassen. Sofern Sie die direkte Übertragung der Daten an einen anderen Verantwortlichen verlangen, erfolgt dies nur, soweit es technisch machbar ist.',
      'general_9': 'Auskunft, Berichtigung und Löschung',
      'general_9_1': 'Sie haben im Rahmen der geltenden gesetzlichen Bestimmungen jederzeit das Recht auf unentgeltliche Auskunft über Ihre gespeicherten personenbezogenen Daten, deren Herkunft und Empfänger und den Zweck der Datenverarbeitung und ggf. ein Recht auf Berichtigung oder Löschung dieser Daten. Hierzu sowie zu weiteren Fragen zum Thema personenbezogene Daten können Sie sich jederzeit an uns wenden.',
      
      'general_10': 'Recht auf Einschränkung der Verarbeitung',
      'general_10_1': 'Sie haben das Recht, die Einschränkung der Verarbeitung Ihrer personenbezogenen Daten zu verlangen. Hierzu können Sie sich jederzeit an uns wenden. Das Recht auf Einschränkung der Verarbeitung besteht in folgenden Fällen:',
      'general_10_2_1' : "Wenn Sie die Richtigkeit Ihrer bei uns gespeicherten personenbezogenen	Daten bestreiten, benötigen wir in der Regel Zeit, um dies zu 	überprüfen. Für die Dauer der Prüfung haben Sie das Recht, die 	Einschränkung der Verarbeitung Ihrer personenbezogenen Daten zu verlangen.",
      'general_10_2_2': 'Wenn die Verarbeitung Ihrer personenbezogenen Daten unrechtmäßig geschah/geschieht, können Sie statt der Löschung die Einschränkung 	der Datenverarbeitung verlangen.',
      'general_10_2_3': 'Wenn wir Ihre personenbezogenen Daten nicht mehr benötigen, Sie sie 	jedoch zur Ausübung, Verteidigung oder Geltendmachung von 	Rechtsansprüchen benötigen, haben Sie das Recht, statt der 	Löschung die Einschränkung der Verarbeitung Ihrer 	personenbezogenen Daten zu verlangen.',
      'general_10_2_4': 'Wenn 	Sie einen Widerspruch nach Art. 21 Abs. 1 DSGVO eingelegt haben, 	muss eine Abwägung zwischen Ihren und unseren Interessen 	vorgenommen werden. Solange noch nicht feststeht, wessen Interessen 	überwiegen, haben Sie das Recht, die Einschränkung der 	Verarbeitung Ihrer personenbezogenen Daten zu verlangen.',
      'general_10_3': 'Wenn Sie die Verarbeitung Ihrer personenbezogenen Daten eingeschränkt haben, dürfen diese Daten – von ihrer Speicherung abgesehen – nur mit Ihrer Einwilligung oder zur Geltendmachung, Ausübung oder Verteidigung von Rechtsansprüchen oder zum Schutz der Rechte einer anderen natürlichen oder juristischen Person oder aus Gründen eines wichtigen öffentlichen Interesses der Europäischen Union oder eines Mitgliedstaats verarbeitet werden.',
      'general_10_4': 'SSL- bzw. TLS-Verschlüsselung',
      'general_10_4_1': 'Diese Seite nutzt aus Sicherheitsgründen und zum Schutz der Übertragung vertraulicher Inhalte, wie zum Beispiel Bestellungen oder Anfragen, die Sie an uns als Seitenbetreiber senden, eine SSL- bzw. TLS- Verschlüsselung. Eine verschlüsselte Verbindung erkennen Sie daran, dass die Adresszeile des Browsers von „http://“ auf „https://“ wechselt und an dem Schloss-Symbol in Ihrer Browserzeile. Wenn die SSL- bzw. TLS-Verschlüsselung aktiviert ist, können die Daten, die Sie an uns übermitteln, nicht von Dritten mitgelesen werden.',

      'general_11': '4. Datenerfassung auf dieser Website',
      'general_11_0': 'Cookies',
      'general_11_1': "Unsere Internetseiten verwenden so genannte „Cookies“. Cookies sind kleine Datenpakete und richten auf Ihrem Endgerät keinen Schaden an. Sie werden entweder vorübergehend für die Dauer einer Sitzung (Session-Cookies) oder dauerhaft (permanente Cookies) auf Ihrem Endgerät gespeichert. Session-Cookies werden nach Ende Ihres Besuchs automatisch gelöscht. Permanente Cookies bleiben auf Ihrem Endgerät gespeichert, bis Sie diese selbst löschen oder eine automatische Löschung durch Ihren Webbrowser erfolgt.",
      'general_11_2': 'Cookies können von uns (First-Party-Cookies) oder von Drittunternehmen stammen (sog. Third-Party- Cookies). Third-Party-Cookies ermöglichen die Einbindung bestimmter Dienstleistungen von Drittunternehmen innerhalb von Webseiten (z. B. Cookies zur Abwicklung von Zahlungsdienstleistungen).',
      'general_11_3': 'Cookies haben verschiedene Funktionen. Zahlreiche Cookies sind technisch notwendig, da bestimmte Webseitenfunktionen ohne diese nicht funktionieren würden (z. B. die Warenkorbfunktion oder die Anzeige von Videos). Andere Cookies können zur Auswertung des Nutzerverhaltens oder zu Werbezwecken verwendet werden.',

      'general_12': '5. Soziale Medien',
      'general_12_1': 'Instagram',
      'general_12_2': 'Auf dieser Website sind Funktionen des Dienstes Instagram eingebunden. Diese Funktionen werden angeboten durch die Meta Platforms Ireland Limited, 4 Grand Canal Square, Grand Canal Harbour, Dublin 2, Irland. Wenn das Social-Media-Element aktiv ist, wird eine direkte Verbindung zwischen Ihrem Endgerät und dem Instagram-Server hergestellt. Instagram erhält dadurch Informationen über den Besuch dieser Website durch Sie. Wenn Sie in Ihrem Instagram-Account eingeloggt sind, können Sie durch Anklicken des Instagram-Buttons die Inhalte dieser Website mit Ihrem Instagram-Profil verlinken. Dadurch kann Instagram den Besuch dieser Website Ihrem Benutzerkonto zuordnen. Wir weisen darauf hin, dass wir als Anbieter der Seiten keine Kenntnis vom Inhalt der übermittelten Daten sowie deren Nutzung durch Instagram erhalten. Die Nutzung dieses Dienstes erfolgt auf Grundlage Ihrer Einwilligung nach Art. 6 Abs. 1 lit. a DSGVO und § 25 Abs. 1 TTDSG. Die Einwilligung ist jederzeit widerrufbar. Soweit mit Hilfe des hier beschriebenen Tools personenbezogene Daten auf unserer Website erfasst und an Facebook bzw. Instagram weitergeleitet werden, sind wir und die Meta Platforms Ireland Limited, 4 Grand Canal Square, Grand Canal Harbour, Dublin 2, Irland gemeinsam für diese Datenverarbeitung verantwortlich (Art. 26 DSGVO). Die gemeinsame Verantwortlichkeit beschränkt sich dabei ausschließlich auf die Erfassung der Daten und deren Weitergabe an Facebook bzw. Instagram. Die nach der Weiterleitung erfolgende Verarbeitung durch Facebook bzw. Instagram ist nicht Teil der gemeinsamen Verantwortung. Die uns gemeinsam obliegenden Verpflichtungen wurden in einer Vereinbarung über gemeinsame Verarbeitung festgehalten.',
      'general_12_3': 'Den Wortlaut der Vereinbarung finden Sie unter:',
      'general_12_4': 'Laut dieser Vereinbarung sind wir für die Erteilung der Datenschutzinformationen beim Einsatz des Facebook- bzw. Instagram-Tools und für die datenschutzrechtlich sichere Implementierung des Tools auf unserer Website verantwortlich. Für die Datensicherheit der Facebook bzw. Instagram-Produkte ist Facebook verantwortlich. Betroffenenrechte (z. B. Auskunftsersuchen) hinsichtlich der bei Facebook bzw. Instagram verarbeiteten Daten können Sie direkt bei Facebook geltend machen. Wenn Sie dieBetroffenenrechte bei uns geltend machen, sind wir verpflichtet, diese an Facebook weiterzuleiten.',
      'general_12_5': "Die Datenübertragung in die USA wird auf die Standardvertragsklauseln der EU-Kommission gestützt. Details finden Sie hier:",
      'general_12_6': "Weitere Informationen hierzu finden Sie in der Datenschutzerklärung von Instagram:",
      'general_12_7': 'Das Unternehmen verfügt über eine Zertifizierung nach dem „EU-US Data Privacy Framework“ (DPF). Der DPF ist ein Übereinkommen zwischen der Europäischen Union und den USA, der die Einhaltung europäischer Datenschutzstandards bei Datenverarbeitungen in den USA gewährleisten soll. Jedes nach dem DPF zertifizierte Unternehmen verpflichtet sich, diese Datenschutzstandards einzuhalten. Weitere Informationen hierzu erhalten Sie vom Anbieter unter folgendem Link:',

      'public': '6. Plugins and Tools',
      'public_1': 'YouTube mit erweitertem Datenschutz',
      'public_0': 'Diese Website bindet Videos der Website YouTube ein. Betreiber der Website ist die Google Ireland Limited („Google”), Gordon House, Barrow Street, Dublin 4, Irland.',
      'public_2': "Wenn Sie eine dieser Website besuchen, auf denen YouTube eingebunden ist, wird eine Verbindung zu den Servern von YouTube hergestellt. Dabei wird dem YouTube-Server mitgeteilt, welche unserer Seiten Sie besucht haben. Wenn Sie in Ihrem YouTube-Account eingeloggt sind, ermöglichen Sie YouTube, Ihr Surfverhalten direkt Ihrem persönlichen Profil zuzuordnen. Dies können Sie verhindern, indem Sie sich aus Ihrem YouTube-Account ausloggen.",
      'public_3': "Wir nutzen YouTube im erweiterten Datenschutzmodus. Videos, die im erweiterten Datenschutzmodus abgespielt werden, werden nach Aussage von YouTube nicht zur Personalisierung des Surfens auf YouTube eingesetzt. Anzeigen, die im erweiterten Datenschutzmodus ausgespielt werden, sind ebenfalls nicht personalisiert. Im erweiterten Datenschutzmodus werden keine Cookies gesetzt. Stattdessen werden jedoch sogenannte Local Storage Elemente im Browser des Users gespeichert, die ähnlich wie Cookies personenbezogene Daten beinhalten und zur Wiedererkennung eingesetzt werden können. Details zum erweiterten Datenschutzmodus finden Sie hier:",
      'public_4': "Die Nutzung von YouTube erfolgt im Interesse einer ansprechenden Darstellung unserer Online-Angebote. Dies stellt ein berechtigtes Interesse im Sinne von Art. 6 Abs. 1 lit. f DSGVO dar. Sofern eine entsprechende Einwilligung abgefragt wurde, erfolgt die Verarbeitung ausschließlich auf Grundlage von Art. 6 Abs. 1 lit. a DSGVO und § 25 Abs. 1 TTDSG, soweit die Einwilligung die Speicherung von Cookies oder den Zugriff auf Informationen im Endgerät des Nutzers (z. B. Device-Fingerprinting) im Sinne des TTDSG umfasst. Die Einwilligung ist jederzeit widerrufbar.",
      'public_5': "Weitere Informationen über Datenschutz bei YouTube finden Sie in deren Datenschutzerklärung unter:",
      'public_6': "Das Unternehmen verfügt über eine Zertifizierung nach dem „EU-US Data Privacy Framework“ (DPF). Der DPF ist ein Übereinkommen zwischen der Europäischen Union und den USA, der die Einhaltung europäischer Datenschutzstandards bei Datenverarbeitungen in den USA gewährleisten soll. Jedes nach dem DPF zertifizierte Unternehmen verpflichtet sich, diese Datenschutzstandards einzuhalten. Weitere Informationen hierzu erhalten Sie vom Anbieter unter folgendem Link:",
      'public_7': "Google Fonts (local hosting)",
      'public_8': "Diese Seite nutzt zur einheitlichen Darstellung von Schriftarten so genannte Google Fonts, die von Google bereitgestellt werden. Die Google Fonts sind lokal installiert. Eine Verbindung zu Servern von Google findet dabei nicht statt.",
      'public_9': "Weitere Informationen zu Google Fonts finden Sie unter https://developers.google.com/fonts/faq und in der Datenschutzerklärung von Google: https://policies.google.com/privacy?hl=de."
    }
  }

  constructor() {
    if(this.isEnglish) {
      this.now = this.content['en'];
    } else {
      this.now = this.content['ge'];
    }
  }

  changeLang() {
    this.isEnglish = !this.isEnglish;
    if(this.isEnglish) {
      this.now = this.content['en'];
    } else {
      this.now = this.content['ge'];
    }
  }
}
